package com.kiroule.example.mybatis.address;

import com.google.common.base.Objects;

import java.util.Date;

public class Address {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.address_id
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Short addressId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String address;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.address2
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String address2;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.district
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String district;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.city_id
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Short cityId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.postal_code
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String postalCode;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.phone
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String phone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column address.last_update
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Date lastUpdate;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.address_id
   *
   * @return the value of address.address_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Short getAddressId() {
    return addressId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * address.address_id
   *
   * @param addressId the value for address.address_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setAddressId(Short addressId) {
    this.addressId = addressId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.address
   *
   * @return the value of address.address
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getAddress() {
    return address;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column address.address
   *
   * @param address the value for address.address
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setAddress(String address) {
    this.address = address == null ? null : address.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.address2
   *
   * @return the value of address.address2
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getAddress2() {
    return address2;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column address.address2
   *
   * @param address2 the value for address.address2
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setAddress2(String address2) {
    this.address2 = address2 == null ? null : address2.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.district
   *
   * @return the value of address.district
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getDistrict() {
    return district;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column address.district
   *
   * @param district the value for address.district
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setDistrict(String district) {
    this.district = district == null ? null : district.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.city_id
   *
   * @return the value of address.city_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Short getCityId() {
    return cityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column address.city_id
   *
   * @param cityId the value for address.city_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setCityId(Short cityId) {
    this.cityId = cityId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.postal_code
   *
   * @return the value of address.postal_code
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getPostalCode() {
    return postalCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * address.postal_code
   *
   * @param postalCode the value for address.postal_code
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode == null ? null : postalCode.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column address.phone
   *
   * @return the value of address.phone
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column address.phone
   *
   * @param phone the value for address.phone
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setPhone(String phone) {
    this.phone = phone == null ? null : phone.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * address.last_update
   *
   * @return the value of address.last_update
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Date getLastUpdate() {
    return lastUpdate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * address.last_update
   *
   * @param lastUpdate the value for address.last_update
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o) return true;
    if (!(o instanceof Address)) return false;

    final Address address = (Address) o;

    if (addressId != null ? !addressId.equals(address.addressId) : address.addressId != null)
      return false;

    return true;
  }

  @Override
  public int hashCode() {
    return addressId != null ? addressId.hashCode() : 0;
  }

  @Override
  public String toString() {
    return Objects.toStringHelper(this)
        .add("addressId", addressId)
        .add("address", address)
        .add("address2", address2)
        .add("district", district)
        .add("cityId", cityId)
        .add("postalCode", postalCode)
        .add("phone", phone)
        .add("lastUpdate", lastUpdate)
        .toString();
  }

}