package com.kiroule.example.mybatis.address;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddressMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int countByExample(AddressExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int deleteByExample(AddressExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int deleteByPrimaryKey(Short addressId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int insert(Address record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int insertSelective(Address record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  List<Address> selectByExample(AddressExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  Address selectByPrimaryKey(Short addressId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int updateByExample(@Param("record") Address record, @Param("example") AddressExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int updateByPrimaryKeySelective(Address record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table address
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  int updateByPrimaryKey(Address record);
}