package com.kiroule.example.mybatis.customer;

import com.google.common.base.Objects;

import java.util.Date;

public class Customer {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.customer_id
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Short customerId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.store_id
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Byte storeId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.first_name
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String firstName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.last_name
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String lastName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.email
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private String email;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.address_id
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Short addressId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.active
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Boolean active = true;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.create_date
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Date createDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column customer.last_update
   *
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  private Date lastUpdate;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.customer_id
   *
   * @return the value of customer.customer_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Short getCustomerId() {
    return customerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.customer_id
   *
   * @param customerId the value for customer.customer_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setCustomerId(Short customerId) {
    this.customerId = customerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.store_id
   *
   * @return the value of customer.store_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Byte getStoreId() {
    return storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.store_id
   *
   * @param storeId the value for customer.store_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setStoreId(Byte storeId) {
    this.storeId = storeId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.first_name
   *
   * @return the value of customer.first_name
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getFirstName() {
    return firstName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.first_name
   *
   * @param firstName the value for customer.first_name
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setFirstName(String firstName) {
    this.firstName = firstName == null ? null : firstName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.last_name
   *
   * @return the value of customer.last_name
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getLastName() {
    return lastName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.last_name
   *
   * @param lastName the value for customer.last_name
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setLastName(String lastName) {
    this.lastName = lastName == null ? null : lastName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.email
   *
   * @return the value of customer.email
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column customer.email
   *
   * @param email the value for customer.email
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setEmail(String email) {
    this.email = email == null ? null : email.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.address_id
   *
   * @return the value of customer.address_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Short getAddressId() {
    return addressId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.address_id
   *
   * @param addressId the value for customer.address_id
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setAddressId(Short addressId) {
    this.addressId = addressId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.active
   *
   * @return the value of customer.active
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Boolean getActive() {
    return active;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column customer.active
   *
   * @param active the value for customer.active
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.create_date
   *
   * @return the value of customer.create_date
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Date getCreateDate() {
    return createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.create_date
   *
   * @param createDate the value for customer.create_date
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column
   * customer.last_update
   *
   * @return the value of customer.last_update
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public Date getLastUpdate() {
    return lastUpdate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column
   * customer.last_update
   *
   * @param lastUpdate the value for customer.last_update
   * @mbggenerated Fri Dec 27 16:10:16 EST 2013
   */
  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o) return true;
    if (!(o instanceof Customer)) return false;

    final Customer customer = (Customer) o;

    if (!email.equals(customer.email)) return false;

    return true;
  }

  @Override
  public int hashCode() {
    return email.hashCode();
  }

  @Override
  public String toString() {
    return Objects.toStringHelper(this)
        .add("customerId", customerId)
        .add("storeId", storeId)
        .add("firstName", firstName)
        .add("lastName", lastName)
        .add("email", email)
        .add("addressId", addressId)
        .add("active", active)
        .add("createDate", createDate)
        .add("lastUpdate", lastUpdate)
        .toString();
  }
}